import React from 'react';
import Head from 'next/head';
import styled from 'styled-components';
import About from '../../components/Sections/Intro';

const Wrapper = styled.div`
  background-color: ${(props) => props.theme.color.background};
  transition: background-color 0.25s linear;
  width: 100%;
`;

const homepage = () => {
  return (
    <Wrapper>
      <Head>
        <title>Dayoung Kim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <About />
    </Wrapper>
  );
};

export default homepage;
