import React from 'react';
import Head from 'next/head';
import styled from 'styled-components';
import Button from '@mui/material/Button';

const ThemeText = styled.div`
  color: ${(props) => props.theme.color.paragraph};
`;

const Wrapper = styled.div`
  background-color: ${(props) => props.theme.color.background};
  transition: background-color 0.25s linear;
`;

const homepage = () => {
  return (
    <Wrapper>
      <Head>
        <title>Dayoung Kim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeText>Do you see this </ThemeText>
      <div>
        Simply put, a paragraph is a collection of sentences all related to a
        central topic, idea, or theme. Paragraphs act as structural tools for
        writers to organize their thoughts into an ideal progression, and they
        also help readers process those thoughts effortlessly. Imagine how much
        harder reading and writing would be if everything was just one long
        block of text. There’s a lot of flexibility when it comes to writing
        paragraphs, but if there’s one steadfast rule, it’s this: Paragraphs
        should relate to one main topic or point. The paragraph itself often
        contains multiple points spanning several sentences, but they should all
        revolve around one core theme. Just as sentences build upon each other
        to communicate the paragraph’s core theme, paragraphs work together to
        communicate the core theme of the writing as a whole. That’s the basic
        idea, but in practice there’s more to it. Let’s look at the four main
        types of paragraphs to learn how and when to use them. Expository
        paragraphs Essays, academic papers, and journalistic articles mainly use
        expository paragraphs to thoroughly explain an individual point. These
        paragraphs rely on data, statistics, or citations from other sources to
        present facts and build up to an irrefutable conclusion. Descriptive
        paragraphs Common in fiction and certain styles of journalistic or other
        nonfiction writing, a descriptive paragraph contains various details of
        the same thing, with each sentence adding new insight. A paragraph in a
        horror novel might describe how it feels walking around the woods alone;
        a love letter’s paragraph might focus on the details of your significant
        other’s eyes. No matter the context, descriptive paragraphs are meant to
        provide the clearest picture of your subject. Persuasive paragraphs For
        editorials and opinion pieces, persuasive paragraphs are meant to
        convince the reader of a specific point, with each sentence presenting
        evidence or reasoning to support that point. Like expository paragraphs,
        persuasive paragraphs may contain data and statistics, but here, these
        work to support an opinion rather than verify a fact. The trick to
        writing persuasive paragraphs is knowing how to assert your opinion
        without sounding preachy. Read More: How to Write a Persuasive Essay
        Narrative paragraphs If you’re telling a story, fiction or nonfiction,
        you’ll need to break up the action into digestible segments so your
        reader doesn’t get confused. That’s the purpose of narrative paragraphs:
        they break up sequential actions into related chunks, with one leading
        into the next, so that the reader can remain focused on the storyline.
        They don’t use evidence or supporting arguments like the other paragraph
        types, but they still abide by the main rule of paragraphs about unity.
        How to write a paragraph Knowing the different types of paragraphs is
        helpful for outlining a piece, but it doesn’t tell you how to write one.
        Let’s move on to some hands-on tips for writing a perfect paragraph,
        starting with a sample written in the academic paragraph structure of
        essays and school papers: Despite the typos we see in texts and social
        media, professional environments still value good grammar. For hiring
        managers, a command of grammar offers honest insight into an applicant’s
        intelligence, dedication, attention to detail, and professionalism, not
        to mention communication skills. Good grammar can even land you that
        promotion: According to a 2013 study, professionals who have been
        promoted six to nine times made 45 percent fewer grammar mistakes than
        those promoted one to four times. Learning the difference between there,
        their, and they’re isn’t just about speaking properly—it’s also a good
        career move! Academic paragraphs use a simple-but-efficient structure
        consisting of four parts: 1. Topic sentence Despite the typos we see in
        texts and social media, professional environments still value good
        grammar. Also known as the “paragraph leader,” your topic sentence
        should introduce the concept and communicate what the paragraph is
        about. Be careful not to squeeze your entire point into this first
        sentence—you just need to say enough so that the reader knows what the
        rest will be about. 2. Development For hiring managers, a command of
        grammar offers honest insight into an applicant’s intelligence,
        dedication, attention to detail, and professionalism, not to mention
        communication skills. Your second and maybe third sentences are where
        you elaborate on your point. All the nonessential information that
        didn’t fit in your topic sentence goes here. The goal is that the reader
        fully understands the point, so feel free to include citations or
        assertions from other sources for stronger communication. 3. Support
        Good grammar can even land you that promotion: According to a 2013
        study, professionals who have been promoted six to nine times made 45
        percent fewer grammar mistakes than those promoted one to four times.
        Here’s where you get down to brass tacks: Present your evidence, data,
        statistics, logical conclusions, persuasive opinion, real-life or
        hypothetical examples, etc.—anything that confirms your initial
        statement. 4. Summary Learning the difference between there, their, and
        they’re isn’t just about speaking properly—it’s also a good career move!
        Last, you want to end by summing up or evaluating your main point—what
        conclusion can your reader draw from your argument? In addition to
        wrapping things up, your summary should also follow the best practices
        for writing conclusions. Advanced tips for writing paragraphs How long
        should a paragraph be? There are no hard limits to how long or short a
        paragraph can be, but typically three to five sentences will suffice.
        Sometimes you may opt for only a single sentence to add emphasis or
        effect, while other times you’ll need more than five sentences to
        present all your evidence. Use your discretion—but err on the side of
        too short instead of too long. Parallel structure In sentence
        construction, parallelism refers to using consistent structure between
        two clauses or phrases (i.e., saying I prefer trains over buses instead
        of I prefer trains over a bus). That same principle applies to
        paragraphs within a greater text: Each paragraph should have a similar
        structure for the sake of consistency. Parallelism is crucial when
        writing about comparisons or using a point-counterpart format. If you’re
        comparing two or more arguments, it’s best to maintain the same
        structure for both arguments (and the paragraphs that explain them).
        Typically, the two most common formats are known as block and
        point-by-point. Let’s say you’re writing an essay comparing apples and
        oranges. Block structure would use an individual paragraph discussing
        everything about apples—taste, appearance, etc.—and then follow it with
        another individual paragraph discussing those same attributes for
        oranges. Point-by-point structure, however, would mix it up a little.
        The first paragraph might center around taste and include data about
        both apples and oranges. Then the second paragraph would move on to a
        new point, like appearance, and would likewise include information on
        both apples and oranges. Neither format is inherently better than the
        other—the best choice depends on the topic and context. The important
        thing is that you stick with your choice throughout the entire piece;
        switching randomly between formats is considered poor writing.
        Transitions One of the hardest parts of writing involves transitions.
        Good writing appears seamless, flowing from one point to another. But
        what do you do if the individual points on their own are disjointed or
        unrelated? That’s when transitions come in handy—they’re a way to move
        to a new point without being abrupt or jarring. Basic transitions can be
        as simple as adding linking words to the beginning of a sentence:
        however, by contrast, in addition, on the other hand, etc. If you’re
        creating a list, you can link each item together using ordinals (first,
        second, etc.) or more casual connectors like for starters, next, and
        last. The same rules for transitioning from sentence to sentence apply
        just as well when transitioning from paragraph to paragraph.
      </div>
      <Button variant="contained">Hello MUI Button component?</Button>
    </Wrapper>
  );
};

export default homepage;
