import React from 'react';
import Head from 'next/head';
import styled from 'styled-components';
import Button from '@mui/material/Button';

const ThemeText = styled.div`
  color: ${(props) => props.theme.color.secondary};
`;

const Wrapper = styled.div`
  background-color: ${(props) => props.theme.color.background};
`;

const homepage = () => {
  return (
    <Wrapper>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeText>Do you see this</ThemeText>
      <Button variant="contained">Hello MUI Button component?</Button>
    </Wrapper>
  );
};

export default homepage;
