import Head from 'next/head';
import styled from 'styled-components';

const ThemeText = styled.div`
  color: ${(props) => props.theme.color.secondary};
`;

const Wrapper = styled.div`
  background-color: ${(props) => props.theme.color.background};
`;

export default function Home() {
  return (
    <Wrapper>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeText>Do you see this</ThemeText>
    </Wrapper>
  );
}
