import Head from 'next/head';
import styled from 'styled-components';
import styles from '../styles/Home.module.css';

const ThemeText = styled.div`
  color: ${(props) => props.theme.color.main};
`;

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <span>aljdf;lkS</span>
      <ThemeText>Do you see this</ThemeText>
    </div>
  );
}
