name: main pull request

on:
  push:
      branches: ["main"]
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: yarn install
        
      - name: Build page
        run: npm run build
        
      
      
        
